# Generated by Django 4.1.7 on 2023-08-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=222)),
                ('food', models.CharField(max_length=222)),
                ('wifi', models.CharField(max_length=222)),
                ('water', models.CharField(max_length=222)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
