# Generated by Django 4.1.7 on 2023-08-02 08:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
